# Generated by Django 5.0.2 on 2024-04-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textract', '0004_alter_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
